listener 1883
allow_anonymous true
log_type all
persistence false

######

CREATE DATABASE smart_parking_db_django;

CREATE USER inteliparking WITH PASSWORD 'nopassword';

ALTER ROLE inteliparking SET client_encoding TO 'utf8';
ALTER ROLE inteliparking SET default_transaction_isolation TO 'read committed';
ALTER ROLE inteliparking SET timezone TO 'UTC';

ALTER DATABASE smart_parking_db_django OWNER TO inteliparking;

\c smart_parking_db_django

GRANT ALL ON SCHEMA public TO inteliparking;
ALTER SCHEMA public OWNER TO inteliparking;



server {
    listen 80;
    server_name 192.168.2.238;

    # FRONTEND
    location / {
        root /home/parkingadmin/inteliParking/frontend;
        index index.html;
        try_files $uri /index.html;
    }

    # DJANGO API
    location /api/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # WEBSOCKET
    location /ws/ {
        proxy_pass http://127.0.0.1:8001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
    }
}

##########