SIMULATION_DATA = {
    "META_DATA": [
        {
            "area_code": "BPF2",
            "offline_percentage": 10,
            "available_percentage": 60,
            "occupied_percentage": 30,
            "update_interval": 5,
            "change_probability": 0.2,
        }
    ],
    "PARKING_DEVICES_ESP32": [
        {
            "device_id": 1,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "A-01", "section_code": "A"},
                {"spot_code": "A-02", "section_code": "A"},
                {"spot_code": "A-03", "section_code": "A"},
                {"spot_code": "A-04", "section_code": "A"},
                {"spot_code": "A-05", "section_code": "A"},
                {"spot_code": "A-06", "section_code": "A"},
                {"spot_code": "A-07", "section_code": "A"},
                {"spot_code": "A-08", "section_code": "A"},
            ],
        },
        {
            "device_id": 2,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "A-09", "section_code": "A"},
                {"spot_code": "A-10", "section_code": "A"},
                {"spot_code": "A-12", "section_code": "A"},
                {"spot_code": "B-01", "section_code": "B"},
                {"spot_code": "B-02", "section_code": "B"},
                {"spot_code": "B-03", "section_code": "B"},
                {"spot_code": "B-04", "section_code": "B"},
                {"spot_code": "B-05", "section_code": "B"},
            ],
        },
        {
            "device_id": 3,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "B-06", "section_code": "B"},
                {"spot_code": "B-07", "section_code": "B"},
                {"spot_code": "B-08", "section_code": "B"},
                {"spot_code": "B-09", "section_code": "B"},
                {"spot_code": "B-10", "section_code": "B"},
                {"spot_code": "B-11", "section_code": "B"},
                {"spot_code": "B-12", "section_code": "B"},
                {"spot_code": "C-01", "section_code": "C"},
            ],
        },
        {
            "device_id": 4,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "C-02", "section_code": "C"},
                {"spot_code": "C-03", "section_code": "C"},
                {"spot_code": "C-04", "section_code": "C"},
                {"spot_code": "C-05", "section_code": "C"},
                {"spot_code": "C-06", "section_code": "C"},
                {"spot_code": "C-07", "section_code": "C"},
                {"spot_code": "C-08", "section_code": "C"},
                {"spot_code": "C-09", "section_code": "C"},
            ],
        },
        {
            "device_id": 5,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "C-02", "section_code": "C"},
                {"spot_code": "C-03", "section_code": "C"},
                {"spot_code": "C-04", "section_code": "C"},
                {"spot_code": "C-05", "section_code": "C"},
                {"spot_code": "C-06", "section_code": "C"},
                {"spot_code": "C-07", "section_code": "C"},
                {"spot_code": "C-08", "section_code": "C"},
                {"spot_code": "C-09", "section_code": "C"},
            ],
        },
        {
            "device_id": 6,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "C-10", "section_code": "C"},
                {"spot_code": "C-11", "section_code": "C"},
                {"spot_code": "C-12", "section_code": "C"},
                {"spot_code": "D-01", "section_code": "D"},
                {"spot_code": "D-02", "section_code": "D"},
                {"spot_code": "D-03", "section_code": "D"},
                {"spot_code": "D-04", "section_code": "D"},
                {"spot_code": "D-05", "section_code": "D"},
            ],
        },
        {
            "device_id": 7,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "D-06", "section_code": "D"},
                {"spot_code": "D-07", "section_code": "D"},
                {"spot_code": "D-08", "section_code": "D"},
                {"spot_code": "D-09", "section_code": "D"},
                {"spot_code": "D-10", "section_code": "D"},
                {"spot_code": "D-11", "section_code": "D"},
                {"spot_code": "D-12", "section_code": "D"},
                {"spot_code": "E-01", "section_code": "E"},
            ],
        },
        {
            "device_id": 8,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "E-02", "section_code": "E"},
                {"spot_code": "E-03", "section_code": "E"},
                {"spot_code": "E-04", "section_code": "E"},
                {"spot_code": "E-05", "section_code": "E"},
                {"spot_code": "E-06", "section_code": "E"},
                {"spot_code": "E-07", "section_code": "E"},
                {"spot_code": "E-08", "section_code": "E"},
                {"spot_code": "E-09", "section_code": "E"},
            ],
        },
        {
            "device_id": 9,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "E-10", "section_code": "E"},
                {"spot_code": "E-11", "section_code": "E"},
                {"spot_code": "E-12", "section_code": "E"},
                {"spot_code": "F-01", "section_code": "F"},
                {"spot_code": "F-02", "section_code": "F"},
                {"spot_code": "F-03", "section_code": "F"},
                {"spot_code": "F-04", "section_code": "F"},
                {"spot_code": "F-05", "section_code": "F"},
            ],
        },
        {
            "device_id": 10,
            "area_code": "BPF2",
            "spots": [
                {"spot_code": "F-06", "section_code": "F"},
                {"spot_code": "F-07", "section_code": "F"},
                {"spot_code": "F-08", "section_code": "F"},
                {"spot_code": "F-09", "section_code": "F"},
                {"spot_code": "F-10", "section_code": "F"},
                {"spot_code": "F-11", "section_code": "F"},
                {"spot_code": "F-12", "section_code": "F"},
            ],
        },
    ],
}
