"""area_code

Revision ID: 200271e9d3ff
Revises: ff701da0ac21
Create Date: 2026-01-14 12:52:16.294812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "200271e9d3ff"
down_revision: Union[str, Sequence[str], None] = "ff701da0ac21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parking_areas", sa.Column("area_code", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_parking_areas_area_code"), "parking_areas", ["area_code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parking_areas_area_code"), table_name="parking_areas")
    op.drop_column("parking_areas", "area_code")
    # ### end Alembic commands ###
