"""Initial_Migration

Revision ID: 8ed273d6843d
Revises:
Create Date: 2026-01-07 12:25:31.909455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ed273d6843d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("logo", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admins_email"), "admins", ["email"], unique=True)
    op.create_index(op.f("ix_admins_id"), "admins", ["id"], unique=False)
    op.create_table(
        "parking_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("display_height", sa.Integer(), nullable=True),
        sa.Column("display_width", sa.Integer(), nullable=True),
        sa.Column("total_spots", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parking_areas_id"), "parking_areas", ["id"], unique=False)
    op.create_index(
        op.f("ix_parking_areas_name"), "parking_areas", ["name"], unique=True
    )
    op.create_table(
        "parking_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("section_code", sa.String(), nullable=True),
        sa.Column("parking_area_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parking_area_id"],
            ["parking_areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parking_sections_id"), "parking_sections", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_parking_sections_name"), "parking_sections", ["name"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_uid", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("wifi_password", sa.String(), nullable=True),
        sa.Column("no_of_sensor_nodes", sa.Integer(), nullable=True),
        sa.Column("active_sensor_nodes", sa.Integer(), nullable=True),
        sa.Column("parking_area_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parking_area_id"],
            ["parking_areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["parking_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_devices_device_uid"), "devices", ["device_uid"], unique=True
    )
    op.create_index(op.f("ix_devices_id"), "devices", ["id"], unique=False)
    op.create_table(
        "spots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spot_code", sa.String(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("is_occupied", sa.Boolean(), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["parking_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spots_id"), "spots", ["id"], unique=False)
    op.create_index(op.f("ix_spots_spot_code"), "spots", ["spot_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spots_spot_code"), table_name="spots")
    op.drop_index(op.f("ix_spots_id"), table_name="spots")
    op.drop_table("spots")
    op.drop_index(op.f("ix_devices_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_device_uid"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_parking_sections_name"), table_name="parking_sections")
    op.drop_index(op.f("ix_parking_sections_id"), table_name="parking_sections")
    op.drop_table("parking_sections")
    op.drop_index(op.f("ix_parking_areas_name"), table_name="parking_areas")
    op.drop_index(op.f("ix_parking_areas_id"), table_name="parking_areas")
    op.drop_table("parking_areas")
    op.drop_index(op.f("ix_admins_id"), table_name="admins")
    op.drop_index(op.f("ix_admins_email"), table_name="admins")
    op.drop_table("admins")
    # ### end Alembic commands ###
