""""Make_spot_code_unique_per_section_only"

Revision ID: 3914d7808888
Revises: 8ed273d6843d
Create Date: 2026-01-07 12:41:07.950128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3914d7808888'
down_revision: Union[str, Sequence[str], None] = '8ed273d6843d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spots_spot_code'), table_name='spots')
    op.create_index(op.f('ix_spots_spot_code'), 'spots', ['spot_code'], unique=False)
    op.create_unique_constraint('_section_spot_uc', 'spots', ['section_id', 'spot_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_section_spot_uc', 'spots', type_='unique')
    op.drop_index(op.f('ix_spots_spot_code'), table_name='spots')
    op.create_index(op.f('ix_spots_spot_code'), 'spots', ['spot_code'], unique=True)
    # ### end Alembic commands ###
