"""Refactor Spot Status

Revision ID: a8c7cdb1e98a
Revises: 3914d7808888
Create Date: 2026-01-08 15:35:42.197043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c7cdb1e98a'
down_revision: Union[str, Sequence[str], None] = '3914d7808888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('mac_address', sa.String(), nullable=True))
    op.drop_column('devices', 'wifi_password')
    op.add_column('spots', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('spots', 'is_occupied')
    op.drop_column('spots', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('spots', sa.Column('is_occupied', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('spots', 'status')
    op.add_column('devices', sa.Column('wifi_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('devices', 'mac_address')
    # ### end Alembic commands ###
