"""add_total_section_area

Revision ID: ff701da0ac21
Revises: a8c7cdb1e98a
Create Date: 2026-01-14 10:47:02.798938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff701da0ac21'
down_revision: Union[str, Sequence[str], None] = 'a8c7cdb1e98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_areas', sa.Column('total_sections', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_areas', 'total_sections')
    # ### end Alembic commands ###
