# Generated by Django 5.1.3 on 2026-02-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='max_dist',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='spot',
            name='min_dist',
            field=models.IntegerField(default=50),
        ),
    ]
