# Generated by Django 5.1.3 on 2026-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_spot_max_dist_spot_min_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
    ]
