# Generated by Django 5.1.3 on 2026-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_device_debug_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='debug_mode_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='devices_m2m', to='api.parkingsection'),
        ),
    ]
