# Generated by Django 5.1.3 on 2026-04-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_debug_mode_updated_at_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='offline_last_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], default='AVAILABLE', max_length=50),
        ),
    ]
