# Generated by Django 5.1.3 on 2026-04-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_spot_offline_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='last_raw_status',
            field=models.CharField(default='OFFLINE', max_length=50),
        ),
        migrations.AddField(
            model_name='spot',
            name='raw_status_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
